### ISSUE TITLE
New release: 1.6.1

### ISSUE THREAD

**Issue by fabiscafe** [flathub/io.ark.Desktop#2]
a new release is out now:
https://github.com/ArkEcosystem/desktop-wallet/releases/tag/1.6.0

would be nice if you could update it :+1:

**Comment by fabiscafe** [comment]
1.6.1 was released a few days ago
https://github.com/ArkEcosystem/desktop-wallet/releases/tag/1.6.1

**Comment by TingPing** [comment]
If you could submit a PR updating it like this: https://github.com/flathub/io.ark.Desktop/commit/b8d78b866f43cdff381e75bcbd4aac4aa9633922 that would be very helpful.
