### ISSUE TITLE
EOL Ark Wallet

### ISSUE THREAD

**Issue by bbhtt** [flathub/io.ark.Desktop#7]
The repository is archived https://github.com/ArkEcosystem/desktop-wallet but I couldn't find an explanation.

**Comment by razzeee** [comment]
I guess due to this 
![image](https://github.com/flathub/io.ark.Desktop/assets/5943908/bc92de4c-ad0b-4aef-9d2b-056b858c0c08)

**Comment by bbhtt** [comment]
Yea, looks like they added it later on March 23 2023

**Comment by hfiguiere** [comment]
the question is whether it's important to keep it up (EOL doesn't mean no longer works). But if there is a replacement maybe the replacement should be packaged first and this done as "eol-rebase"

**Comment by hfiguiere** [comment]
but it's in a 5 year old runtime, and proprietary so I guess EOL it the safest path here. Probably need admin help to EOL it.

**Comment by bbhtt** [comment]
If it still works I can update it to the latest version/runtime but I don't have a wallet/account.

Maybe @TingPing knows?

**Comment by TingPing** [comment]
I don't use this. It should be EOL'd.
